sources:
  - id: "opendatahub_adr"
    manifest: "manifests/sources/opendatahub_adr.yaml"
    enabled: true

  - id: "madr"
    manifest: "manifests/sources/madr.yaml"
    enabled: true

  - id: "r2abench"
    manifest: "manifests/sources/r2abench.yaml"
    enabled: true

  - id: "backstage_adrs"
    manifest: "manifests/sources/backstage_adrs.yaml"
    enabled: true

  - id: "k8s_keps"
    manifest: "manifests/sources/k8s_keps.yaml"
    enabled: true

  - id: "sake"
    manifest: "manifests/sources/sake.yaml"
    enabled: true

  - id: "cake"
    manifest: "manifests/sources/cake.yaml"
    enabled: true

  - id: "archbench"
    manifest: "manifests/sources/archbench.yaml"
    enabled: true
